---
apiVersion: v1
kind: Service

metadata:
  name: smart_scaler_agents_manager-service
  namespace: default

spec:
  ports:
  - port: 18002
    protocol: TCP
    targetPort: 18002
  selector:
    service: smart_scaler_agents_manager
  type: ClusterIP