---
apiVersion: v1
kind: Service

metadata:
  name: smart_scaler_api_gateway-service
  namespace: default

spec:
  ports:
  - port: 18001
    protocol: TCP
    targetPort: 18001
  selector:
    service: smart_scaler_api_gateway
  type: NodePort