---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: smartscaler-controller
rules:
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: smartscaler-controller
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: smartscaler-controller
  apiGroup: rbac.authorization.k8s.io