---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler

metadata:
  name: smart_scaler_repo_manager-hpa
  namespace: default

spec:

  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: smart_scaler_repo_manager-deployment

  minReplicas: 1
  maxReplicas: 10

  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50