---
apiVersion: extensions/v1beta2
kind: Deployment

metadata:
  name: smart_scaler_api_gateway-deployment
  namespace: default

spec:
  selector:
    matchLabels:
      app: smart_scaler
      service: smart_scaler_api_gateway
      role: api_gateway

  replicas: 2

  template:
    metadata:
      name: smart_scaler_api_gateway
      labels:
        app: smart_scaler
        service: smart_scaler_api_gateway
        role: api_gateway
    spec:
      containers:
        - name: smart_scaler_api_getaway
          image: smart_scaler_api_gateway:1.0.0
          ports:
          - containerPort: 18001
