---
apiVersion: v1
kind: Service

metadata:
  name: smart_scaler_redis-service

spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    service: smart_scaler_redis
  type: ClusterIP